name: "Apollo Proxy"
description: "Efficient proxy client"
version: "1.0.1"
slug: "apollo_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# ports:
#   80/tcp: 80
#   443/tcp: 443
# host_network: true

options:
  server: "admin.tunl.kubakgroup.com"
  token: "yPAca1Vh51e1TbZjqvfTv8lbkiK3avsw"
  clientname: "apollo"
  user: "admin"
  email: "meernahro11@gmail.com"
  certmagic: "/data/certmagic"

schema:
  server: str
  token: str
  clientname: str
  user: str
  email: str
  certmagic: str


